spring.application.name=BAN
spring.batch.job.enabled=false
spring.batch.jdbc.initialize-schema=always

spring.jpa.database-platform=org.hibernate.community.dialect.SQLiteDialect
spring.datasource.url=jdbc:sqlite:C:\Users\mtara\Documents\Sqlite\BAN.db
spring.datasource.driver-class-name=org.sqlite.JDBC
spring.sql.init.mode=always