spring.application.name=BAN
spring.batch.job.enabled=false
spring.batch.jdbc.initialize-schema=always
spring.jpa.properties.hibernate.search.backend.directory.root=lucene-index
spring.profiles.active=sqlite
