spring.application.name=BAN
spring.batch.job.enabled=false
spring.batch.jdbc.initialize-schema=always
spring.jpa.properties.hibernate.search.backend.directory.root=lucene-index
spring.profiles.active=postgresql


# application.properties
dossier.csv=C:\\Users\\mtara\\Documents\\csv
filtre.codePostal=
filtre.codeInsee=
batch.partition.threads=4
param.recuperation=true
spring.sql.init.mode=always